Change the python_interpreter_target to use an explicit executable target.
This changes the attr used for the `python_interpreter_target` to
resolve the attribute path using the executable attr type rather
than using the ctx.path() call.

This allows the rule to use built targets that output an executable,
which previously led to errors like the following when
`python_interpreter_target` is set to a built file.

```
INFO: Invocation ID: fecae496-23bc-4762-9814-669a53c4ffdc
INFO: Repository pip_deps instantiated at:
  /home/pras/bg/mobile_ws/src/bazel_deps/WORKSPACE:9:13: in <toplevel>
  /home/pras/bg/mobile_ws/src/bazel_deps/workspace/stage1.bzl:49:16: in setup
  /home/pras/.cache/bazel/_bazel_pras/d8fc321f6a6c8010877b61d7c115f8dc/external/rules_python/python/pip.bzl:53:19: in pip_install
Repository rule pip_repository defined at:
  /home/pras/.cache/bazel/_bazel_pras/d8fc321f6a6c8010877b61d7c115f8dc/external/rules_python/python/pip_install/pip_repository.bzl:67:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'pip_deps':
   Traceback (most recent call last):
	File "/home/pras/.cache/bazel/_bazel_pras/d8fc321f6a6c8010877b61d7c115f8dc/external/rules_python/python/pip_install/pip_repository.bzl", line 9, column 39, in _pip_repository_impl
		python_interpreter = rctx.path(target)
Error in path: Not a regular file: /home/pras/.cache/bazel/_bazel_pras/d8fc321f6a6c8010877b61d7c115f8dc/external/org_python/interpreter/bin/python3
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/pras/.cache/bazel/_bazel_pras/d8fc321f6a6c8010877b61d7c115f8dc/external/rules_python/python/pip_install/pip_repository.bzl", line 9, column 39, in _pip_repository_impl
		python_interpreter = rctx.path(target)
Error in path: Not a regular file: /home/pras/.cache/bazel/_bazel_pras/d8fc321f6a6c8010877b61d7c115f8dc/external/org_python/interpreter/bin/python3
ERROR: Not a regular file: /home/pras/.cache/bazel/_bazel_pras/d8fc321f6a6c8010877b61d7c115f8dc/external/org_python/interpreter/bin/python3

```